---
- hosts: all
  become: yes
  tasks: 
    
  - name: download artifacts
    get_url: 
      url: http://3.16.135.251:8081/nexus/service/local/repositories/jaga/content/hello/hello-world/5/hello-world-5.war
      dest: /usr/share/tomcat
      url_username: jaga
      url_password: jaga
      
  - name: restart tomcat
    systemd: 
      name: tomcat
      state: restarted
