---
- hosts: all
  become: yes
  tasks:
  - name: installing jdk
    apt:
      name: openjdk-8-jre-headless
      update_cache: yes

  - name: installing java
    apt:
      name: openjdk-8-jdk-headless
      state: present
      
  - name: creat tomcat group
    group:
      name: tomcat

  - name: creat tomcat user and add to tomcat group
    user: 
      name: tomcat
      group: tomcat

  - name: creat tomcat directory inside /opt
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download tomcat file and extract to /opt/tomcat
    unarchive: 
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: /opt/tomcat
      remote_src: yes

  - name: change permissions
    file: 
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: u=rwx,g=rwx,o=rwx
      recurse: yes
      state: directory

  - name: copy tomcat service from ansible"
    copy:
      src: tomcat.service
      dest: /etc/systemd/system
      mode: 0755


  - name: start tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true


